# Generated by Django 3.1 on 2022-04-02 14:06

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Ürün Adı', max_length=100, verbose_name='Ürün Adı')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='Slug', null=True, populate_from='product_name', unique=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='Ürün Detay', max_length=500, verbose_name='Ürün Detay')),
                ('price', models.PositiveIntegerField(help_text='Fiyat', verbose_name='Fiyat')),
                ('images', models.ImageField(help_text='Görsel', upload_to='photos/products', verbose_name='Görsel')),
                ('stock', models.PositiveIntegerField(help_text='Stok', verbose_name='Stok')),
                ('is_available', models.BooleanField(default=True, help_text='Aktif', verbose_name='Aktif')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma Tarihi', verbose_name='Oluşturulma Tarihi')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Düzenlenme Tarihi', verbose_name='Düzenlenme Tarihi')),
                ('category', models.ForeignKey(help_text='Kategoriler', on_delete=django.db.models.deletion.CASCADE, to='category.categorymodel', verbose_name='Kategoriler')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('review', models.TextField(blank=True, max_length=250)),
                ('rating', models.FloatField()),
                ('ip', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Ürün', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.productmodel', verbose_name='Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProductReview',
                'verbose_name_plural': 'ProductReviews',
                'db_table': 'ProductReviews',
            },
        ),
        migrations.CreateModel(
            name='ProductVariationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('color', 'Renk'), ('size', 'Beden')], max_length=150)),
                ('variation_value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.productmodel')),
            ],
            options={
                'verbose_name': 'ProductVariation',
                'verbose_name_plural': 'ProductVariations',
                'db_table': 'ProductVariations',
                'ordering': ['-id'],
            },
        ),
    ]
