# Generated by Django 3.1 on 2022-04-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productgallerymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallerymodel',
            options={'verbose_name': 'Product Images', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelTable(
            name='productgallerymodel',
            table='ProductImages',
        ),
    ]
