# Generated by Django 3.1 on 2022-04-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220403_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallerymodel',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='store.productmodel'),
        ),
    ]
