# Generated by Django 3.1 on 2022-04-03 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20220403_2232'),
        ('store', '0004_auto_20220403_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariationmodel',
            options={'ordering': ['-id'], 'verbose_name': 'Product Variation', 'verbose_name_plural': 'Product Variations'},
        ),
        migrations.AlterModelOptions(
            name='reviewratingmodel',
            options={'verbose_name': 'Product Review', 'verbose_name_plural': 'Product Teviews'},
        ),
        migrations.AlterField(
            model_name='productgallerymodel',
            name='image',
            field=models.ImageField(max_length=300, upload_to='store/products', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productgallerymodel',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='store.productmodel', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categorymodel', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Product Detail'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='images',
            field=models.ImageField(upload_to='photos/products', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_name',
            field=models.CharField(help_text='Product Name', max_length=100, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='productvariationmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='productvariationmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='productvariationmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.productmodel', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productvariationmodel',
            name='variation_category',
            field=models.CharField(choices=[('color', 'Renk'), ('size', 'Beden')], max_length=150, verbose_name='Variation Category'),
        ),
        migrations.AlterField(
            model_name='productvariationmodel',
            name='variation_value',
            field=models.CharField(max_length=100, verbose_name='Variation Value'),
        ),
        migrations.AlterField(
            model_name='reviewratingmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='reviewratingmodel',
            name='ip',
            field=models.CharField(blank=True, max_length=50, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='reviewratingmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.productmodel', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='reviewratingmodel',
            name='rating',
            field=models.FloatField(verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='reviewratingmodel',
            name='review',
            field=models.TextField(blank=True, max_length=250, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='reviewratingmodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reviewratingmodel',
            name='subject',
            field=models.CharField(blank=True, max_length=50, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='reviewratingmodel',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='reviewratingmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
