# Generated by Django 3.1 on 2022-04-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='avatar',
            field=models.ImageField(blank=True, default='default/user.jpg', upload_to='userprofile/'),
        ),
    ]
