# Generated by Django 3.1 on 2022-04-02 14:06

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Kategori Adı', max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='Slug', null=True, populate_from='category_name', unique=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='Detay', max_length=500, verbose_name='Detay')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/categories/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Categories',
            },
        ),
    ]
