# Generated by Django 3.1 on 2022-04-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category_name',
            field=models.CharField(help_text='Category Name', max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='description',
            field=models.TextField(help_text='Detail', max_length=500, verbose_name='Detail'),
        ),
    ]
