# Generated by Django 3.1 on 2022-04-02 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, help_text='CartID', max_length=250, unique=True, verbose_name='CartID')),
                ('date_added', models.DateField(auto_now_add=True, help_text='Ekleme Tarihi', verbose_name='Ekleme Tarihi')),
                ('user', models.ForeignKey(help_text='Kullanıcı', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='CartItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Adet', verbose_name='Adet')),
                ('is_active', models.BooleanField(default=True, help_text='Aktif', verbose_name='Aktif')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cart', models.ForeignKey(help_text='Sepet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cart.cartmodel', verbose_name='Sepet')),
                ('product', models.ForeignKey(help_text='Ürün', on_delete=django.db.models.deletion.CASCADE, to='store.productmodel', verbose_name='Ürün')),
                ('user', models.ForeignKey(help_text='Kullanıcı', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('variations', models.ManyToManyField(blank=True, to='store.ProductVariationModel')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'CartItems',
            },
        ),
    ]
