# Generated by Django 3.1 on 2022-04-03 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_auto_20220403_2232'),
        ('orders', '0002_auto_20220403_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproductmodel',
            options={'verbose_name': 'Order Product', 'verbose_name_plural': 'Order Products'},
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='address_title',
            field=models.CharField(max_length=50, verbose_name='Address Title'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='clear_address',
            field=models.CharField(max_length=500, verbose_name='Clear Address'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='ip',
            field=models.CharField(blank=True, max_length=20, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Is Ordered'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_note',
            field=models.CharField(max_length=400, verbose_name='Order Note'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_number',
            field=models.CharField(max_length=100, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_total',
            field=models.FloatField(verbose_name='Order Total'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('New', 'New Order'), ('Receipt', 'Receipt'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='New', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='tax',
            field=models.FloatField(verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orderproductmodel',
            name='created_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Add'),
        ),
        migrations.AlterField(
            model_name='orderproductmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.ordermodel', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderproductmodel',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Ordered'),
        ),
        migrations.AlterField(
            model_name='orderproductmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productmodel', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orderproductmodel',
            name='product_price',
            field=models.FloatField(verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='orderproductmodel',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderproductmodel',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderproductmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orderproductmodel',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.ProductVariationModel', verbose_name='Product Variation'),
        ),
    ]
